import os
from pathlib import Path


def is_file_newer(
    candidate_file: str | bytes | os.PathLike,
    reference_file: str | bytes | os.PathLike,
) -> bool:
    """Check if a candidate file is newer than a reference file.

    This function is useful for build systems or static site generators
    to decide whether a target file needs to be regenerated by comparing
    its last modification time to that of a source or dependency file.

    Args:
        candidate_file (str | bytes | os.PathLike): Path to the file to
            check.
        reference_file (str | bytes | os.PathLike): Path to the file to
            compare against.

    Returns:
        bool: True if the candidate file exists and its modification
            time is more recent than the reference file's, False
            otherwise.

    Examples:
        >>> is_file_newer("output.html", "input.md")
        True
    """
    candidate_file = Path(candidate_file)
    reference_file = Path(reference_file)

    # Get the modification time of the candidate file.
    try:
        candidate_mtime = candidate_file.stat().st_mtime
    except FileNotFoundError:
        return False

    # Get the modification time of the reference file.
    try:
        reference_mtime = reference_file.stat().st_mtime
    except FileNotFoundError:
        return True

    return candidate_mtime > reference_mtime
